apiVersion: v1
kind: Service
metadata:
  name: {{ include "gas-city.mailName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gas-city.labels" . | nindent 4 }}
    app.kubernetes.io/component: mail
spec:
  type: ClusterIP
  selector:
    {{- include "gas-city.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mail
  ports:
  - name: http
    port: 8765
    targetPort: 8765
    protocol: TCP
